version: '3.8'

services:
  minutesai:
    build: .
    container_name: minutesai
    ports:
      - "7860:7860"
    volumes:
      # 모델 캐시를 로컬에 저장 (재시작 시 다시 다운로드 방지)
      - ./models:/root/.cache/whisper
      # output 폴더를 로컬에 마운트
      - ./output:/app/src/output
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
    # GPU 사용 시 주석 해제
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
